package com.my.simplesampletest.jsonobjecttostring;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CASES_BEAN.
 */
public class CasesBean {

    private Long id;
    private Integer bankRead;
    private Integer bankResult;
    private Integer gewRead;
    private Integer gewResult;
    private String policeRead;
    private String policeResult;
    private String ID;
    private String caseName;
    private String caseNo;
    private java.util.Date registerDate;
    private String strDate;

    public CasesBean() {
    }

    public CasesBean(Long id) {
        this.id = id;
    }

    public CasesBean(Long id, Integer bankRead, Integer bankResult, Integer gewRead, Integer gewResult, String policeRead, String policeResult, String ID, String caseName, String caseNo, java.util.Date registerDate, String strDate) {
        this.id = id;
        this.bankRead = bankRead;
        this.bankResult = bankResult;
        this.gewRead = gewRead;
        this.gewResult = gewResult;
        this.policeRead = policeRead;
        this.policeResult = policeResult;
        this.ID = ID;
        this.caseName = caseName;
        this.caseNo = caseNo;
        this.registerDate = registerDate;
        this.strDate = strDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getBankRead() {
        return bankRead;
    }

    public void setBankRead(Integer bankRead) {
        this.bankRead = bankRead;
    }

    public Integer getBankResult() {
        return bankResult;
    }

    public void setBankResult(Integer bankResult) {
        this.bankResult = bankResult;
    }

    public Integer getGewRead() {
        return gewRead;
    }

    public void setGewRead(Integer gewRead) {
        this.gewRead = gewRead;
    }

    public Integer getGewResult() {
        return gewResult;
    }

    public void setGewResult(Integer gewResult) {
        this.gewResult = gewResult;
    }

    public String getPoliceRead() {
        return policeRead;
    }

    public void setPoliceRead(String policeRead) {
        this.policeRead = policeRead;
    }

    public String getPoliceResult() {
        return policeResult;
    }

    public void setPoliceResult(String policeResult) {
        this.policeResult = policeResult;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getCaseName() {
        return caseName;
    }

    public void setCaseName(String caseName) {
        this.caseName = caseName;
    }

    public String getCaseNo() {
        return caseNo;
    }

    public void setCaseNo(String caseNo) {
        this.caseNo = caseNo;
    }

    public java.util.Date getRegisterDate() {
        return registerDate;
    }

    public void setRegisterDate(java.util.Date registerDate) {
        this.registerDate = registerDate;
    }

    public String getStrDate() {
        return strDate;
    }

    public void setStrDate(String strDate) {
        this.strDate = strDate;
    }

}
